# Generated by Django 6.0 on 2025-12-19 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'ordering': ('-created_at',), 'verbose_name': 'Admin profili', 'verbose_name_plural': 'Admin profillari'},
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='To‘liq ismi'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(default='Moderator', max_length=50, verbose_name='Roli'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
