# Generated by Django 6.0 on 2026-02-13 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_adminprofile_options_adminprofile_updated_at_and_more'),
        ('suv_tashish_crm', '0012_business_client_business_courier_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='suv_tashish_crm.business'),
        ),
    ]
