# Generated by Django 6.0 on 2026-01-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier_panel', '0002_alter_courier_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courier',
        ),
    ]
