# Generated by Django 6.0 on 2025-12-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # No model operations: OTP model removed
    ]
