# Generated by Django 6.0 on 2025-12-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottles', models.IntegerField(default=1, verbose_name='Suv miqdori (dona)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Mijoz izohi')),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Kenglik (Latitude)')),
                ('lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Uzunlik (Longitude)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('on_way', "Yo'lda"), ('completed', 'Yetkazildi'), ('canceled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
