# Generated by Django 6.0 on 2025-12-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suv_tashish_crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
