# Generated by Django 6.0 on 2026-01-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suv_tashish_crm', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agreed_to_contract',
            field=models.BooleanField(default=False),
        ),
    ]
