# Generated by Django 6.0 on 2026-01-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suv_tashish_crm', '0003_add_agreed_to_contract'),
        ('suv_tashish_crm', '0007_client_agreed_to_contract'),
    ]

    operations = [
    ]
