# Generated by Django 6.0 on 2026-02-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suv_tashish_crm', '0009_alter_bottlehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bottle_balance',
            field=models.IntegerField(default=1),
        ),
    ]
