# Generated by ChatGPT patch
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suv_tashish_crm", "0010_alter_client_bottle_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="must_change_password",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="courier",
            name="must_change_password",
            field=models.BooleanField(default=True),
        ),
    ]
